export const users = [
  {
    "id": 1,
    "name": "Leanne Graham",
    "username": "Bret",
    "Gender": "Male",
    "email": "Sincere@april.biz",
    "status": "active",
    "status_class": 'active',
    "image": "../images/user.jfif",
  },
  {
    "id": 2,
    "name": "Ervin Howell",
    "username": "Antonette",
    "Gender": "Male",
    "email": "Shanna@melissa.tv",
    "status": "active",
    "status_class": 'active',
    "image": "../images/user_img.jfif",
  },
  {
    "id": 3,
    "name": "Clementine Bauch",
    "username": "Samantha",
    "Gender": "Male",
    "email": "Nathan@yesenia.net",
    "status": "active",
    "status_class": 'active',
    "image": "../images/user2.jfif",
  },
  {
    "id": 4,
    "name": "Patricia Lebsack",
    "username": "Karianne",
    "Gender": "Male",
    "email": "Julianne.OConner@kory.org",
    "status": "active",
    "status_class": 'active',
    "image": "../images/user4.jfif",
  },
  {
    "id": 5,
    "name": "Chelsey Dietrich",
    "username": "Kamren",
    "Gender": "Male",
    "email": "Lucio_Hettinger@annie.ca",
    "status": "active",
    "status_class": 'active',
    "image": "../images/user5.jfif",
  },
  {
    "id": 6,
    "name": "Mrs. Dennis Schulist",
    "username": "Leopoldo_Corkery",
    "Gender": "Male",
    "email": "Karley_Dach@jasper.info",
    "status": "active",
    "status_class": 'active',
    "image": "../images/user6.jfif",
  },
  {
    "id": 7,
    "name": "Kurtis Weissnat",
    "username": "Elwyn.Skiles",
    "Gender": "Male",
    "email": "Telly.Hoeger@billy.biz",
    "status": "active",
    "status_class": 'active',
    "image": "../images/user7.jfif",
  },
  {
    "id": 8,
    "name": "Nicholas Runolfsdottir V",
    "username": "Maxime_Nienow",
    "Gender": "Male",
    "email": "Sherwood@rosamond.me",
    "status": "active",
    "status_class": 'active',
    "image": "../images/user8.jfif",
  },
  {
    "id": 9,
    "name": "Glenna Reichert",
    "username": "Delphine",
    "Gender": "Male",
    "email": "Chaim_McDermott@dana.io",
    "status": "active",
    "status_class": 'active',
    "image": "../images/user2.jfif",
  },
  {
    "id": 10,
    "name": "Clementina DuBuque",
    "username": "Moriah.Stanton",
    "Gender": "Male",
    "email": "Rey.Padberg@karina.biz",
    "status": "active",
    "status_class": 'active',
    "image": "../images/user4.jfif",
  },
  {
    "id": 11,
    "name": "Mrs. Dennis Schulist",
    "username": "Leopoldo_Corkery",
    "Gender": "Male",
    "email": "Karley_Dach@jasper.info",
    "status": "active",
    "status_class": 'active',
    "image": "../images/user6.jfif",
  },
  {
    "id": 12,
    "name": "Kurtis Weissnat",
    "username": "Elwyn.Skiles",
    "Gender": "Male",
    "email": "Telly.Hoeger@billy.biz",
    "status": "active",
    "status_class": 'active',
    "image": "../images/user7.jfif",
    "address": {
      "street": "Rex Trail",
      "suite": "Suite 280",
      "city": "Howemouth",
      "zipcode": "58804-1099",
    },
  },
]